set (CMAKE_SYSTEM_PROCESSOR "aarch64"            CACHE STRING "")
set (CROSS_PREFIX           "aarch64-linux-gnu-" CACHE STRING "")

set (CMAKE_SYSTEM_NAME  "Linux"              CACHE STRING "")
set (CMAKE_C_COMPILER   "${CROSS_PREFIX}gcc" CACHE STRING "")
set (CMAKE_CXX_COMPILER "${CROSS_PREFIX}g++" CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER CACHE STRING "")

set(LIBSYSFS_LIBRARY        "$ENV{LIBSYSFS_PATH}/lib/libsysfs.so")
set(LIBSYSFS_INCLUDE_DIR    "$ENV{LIBSYSFS_PATH}/include")

set(LIBMETAL_LIB 		    "$ENV{LIBMETAL_PATH}/usr/local/lib/libmetal.so")
set(LIBMETAL_INCLUDE_DIR    "$ENV{LIBMETAL_PATH}/usr/local/include")

include_directories(${LIBSYSFS_INCLUDE_DIR})